#!/usr/bin/env python3

import subprocess

from pathlib import Path

OPERATIONS = {
    # "󰐥": "systemctl poweroff",
    # "󰜉": "systemctl reboot",
    # "󰍃": "hyprctl dispatch exit 1",
    "Shutdown": "systemctl poweroff",
    "Reboot": "systemctl reboot",
    "Exit session": "hyprctl dispatch exit 1",
}

# return all the ops (newline separated, UTF-8 encoded)
def list_operations(ops: dict[str, str]) -> str:
    return "\n".join(ops.keys()).encode("UTF-8")
    
# creates a wofi prompt, along with string for dmenu
def show_wofi(conf_path: Path, ops: str) -> str:
    conf_path = "~/.config/wofi/scripts/powermenu.conf"
    command = f"wofi --conf {conf_path}"

    # PIPE for stdin to receive inputs
    # PIPE for stdout to receive outputs
    process = subprocess.Popen(command, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    stdout, stderr = process.communicate(input=ops)
    return stdout

# runs the result returned by wofi
def run_result(result: str) -> bool:
    if ops := OPERATIONS.get(result):
        subprocess.Popen(ops, shell=True)
        return True
    else:
        return False

def main() -> bool:
    conf_path = Path("~/.config/wofi/scripts/powermenu.conf").expanduser()
    ops = list_operations(OPERATIONS)
    selected = show_wofi(conf_path, ops)
    selected_op = selected.decode("UTF-8").rstrip()
    return run_result(selected_op)

if __name__ == "__main__":
    main()
